/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static net.sf.dynamicreports.examples.Templates.boldCenteredStyle;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import static net.sf.dynamicreports.report.builder.DynamicReports.stl;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalTextAlignment;
import net.sf.dynamicreports.report.exception.DRException;

/**
 *
 * @author 
 */
public class Cancel extends javax.swing.JInternalFrame {

  
    private final DefaultTableModel model;


    

    

    /**
     * Creates new form CANCEL
     */
    public Cancel() {
       
        model = new DefaultTableModel();
         
        initComponents();
           showData();
            
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Transaction No. :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 300, 210, 30);

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setText(" ");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(250, 300, 200, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Flight No. :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 100, 120, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 140, 80, 30);

        jTextField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField3.setText(" ");
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField3);
        jTextField3.setBounds(250, 140, 200, 30);

        jButton1.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton1.setText("DONE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(700, 300, 100, 40);

        jTable1.setModel(model);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 860, 140);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setText(" ");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(250, 100, 200, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Departure Time :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 180, 210, 30);

        jTextField6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField6.setText(" ");
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField6);
        jTextField6.setBounds(250, 180, 200, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Departure Date :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 220, 210, 30);

        jTextField7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField7.setText(" ");
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField7);
        jTextField7.setBounds(250, 220, 200, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Origin  :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(460, 100, 130, 30);

        jTextField8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField8.setText(" ");
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField8);
        jTextField8.setBounds(650, 100, 200, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Destination :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(460, 140, 170, 30);

        jTextField9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField9.setText(" ");
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField9);
        jTextField9.setBounds(650, 140, 200, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Payment :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(460, 180, 130, 30);

        jTextField10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField10.setText(" ");
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField10);
        jTextField10.setBounds(650, 180, 200, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Arrival Time :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(460, 220, 170, 30);

        jTextField11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField11.setText(" ");
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField11);
        jTextField11.setBounds(650, 220, 200, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Gender");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 260, 120, 30);

        jTextField12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField12.setText(" ");
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField12);
        jTextField12.setBounds(250, 260, 200, 30);

        jButton2.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("REPORT ");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(560, 300, 130, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Flight :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(460, 260, 120, 22);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.setText(" ");
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField5);
        jTextField5.setBounds(650, 260, 200, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel6.setText("Cancellation");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(280, 10, 360, 57);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
       
        deleteData();
        
     

        
    showData();
        
      Admin   V=new Admin();
           JDesktopPane  desktopPane = getDesktopPane();
           desktopPane.add(V);
           V.setVisible(true);
           this.dispose();
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          loadData();
           insert();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           generateReport();
    }//GEN-LAST:event_jButton2ActionPerformed
  void insert(){
          Connection con = null; 
          PreparedStatement pr=null;
          String qry;
          String url;
          
           
          try{
              
              File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
              qry = "insert into cancellation(flightno,name,Departuretime,Arrivaltime ,Departuredate,Origin,Destination,Payment,Transaction,Gender) values(   ?,?,?,?,?,?,?,?,?,?)";
             
             con = DriverManager.getConnection(url);
             pr=con.prepareStatement(qry);
            
             
             pr.setString(1,jTextField2.getText());
            pr.setString(2,jTextField3.getText());
              
          
              pr.setString(4,jTextField11.getText());
              pr.setString(5,jTextField7.getText());
              pr.setString(6,jTextField8.getText());
              pr.setString(7,jTextField9.getText());
              pr.setString(8,jTextField10.getText());
            pr.setInt( 9,Integer.parseInt(jTextField1.getText()));
            pr.setString(10,jTextField12.getText());
              pr.setString(11,jTextField5.getText());
              
            
            
            
        
              
             
             
             int result=pr.executeUpdate();
            if(result>0)
                
             con.close();
             
             
              
          }catch(Exception e){
              JOptionPane.showMessageDialog(rootPane, e);
              
          }
          
      }

 
    void showData(){
        int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
         File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="select flightno,name, age,  Departuretime,Arrivaltime ,Departuredate,Origin,Destination,Payment,Transaction,Gender ,flight from reservationrecord" ;
        con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
        
    }
      
       void loadData(){
        DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
         
        int rowindex = jTable1.getSelectedRow();
         
                
                
             
            jTextField2.setText(m1.getValueAt(rowindex, 0).toString());
            jTextField3.setText(m1.getValueAt(rowindex,1).toString());
          jTextField6.setText(m1.getValueAt(rowindex,3).toString());
               
              jTextField11.setText(m1.getValueAt(rowindex,4).toString());
               jTextField7.setText(m1.getValueAt(rowindex,5).toString());
                jTextField8.setText(m1.getValueAt(rowindex,6).toString());
                 jTextField9.setText(m1.getValueAt(rowindex,7).toString());
                  jTextField10.setText(m1.getValueAt(rowindex,8).toString());
               jTextField1.setText(m1.getValueAt(rowindex, 9).toString());
              jTextField12.setText(m1.getValueAt(rowindex, 10).toString());
                             jTextField5.setText(m1.getValueAt(rowindex, 11).toString());

    }
      
       void deleteData(){
         Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;

    
    
     DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        
        int rowindex = jTable1.getSelectedRow();
        if(rowindex<0)
        {
            JOptionPane.showMessageDialog(rootPane, "No value is selected to delete");
            return;
        }
            
    
    
    
     try{
       
         File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="delete from reservationrecord where  flightno = "+jTextField2.getText()   ; ;
        con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
         
       
        int result= pr.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
        
      
        
                
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
   
     
     
       

       }
        private void generateReport() {   
    Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
        
        
       
        try {

        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";


// SELECT QUERY 

        qry="select * from cancellation";
        con=DriverManager.getConnection(url);
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }
        
       

                net.sf.dynamicreports.report.builder.style.StyleBuilder columnTitleStyle  = stl.style(boldCenteredStyle)

                                    .setBorder(stl.pen1Point())
                                    .setBackgroundColor(Color.RED);

        
       net.sf.dynamicreports.jasper.builder.JasperReportBuilder report = DynamicReports.report();//a new report
         report
                .setColumnTitleStyle(columnTitleStyle)
               // .setColumnStyle(boldStyle)
                .columns(
                  Columns.column("FLIGHTNO", "flightno",   DataTypes.stringType()),
                        Columns.column("NAME", "Name", DataTypes.stringType()),
                        Columns.column("CONTACT", "Contact", DataTypes.stringType()),
                         
                        Columns.column("DEPARTURETIME", "Departuretime", DataTypes.stringType()),
                       Columns.column("ARRIVALTIME", "Arrivaltime", DataTypes.stringType())       ,
                       Columns.column(" DEPARTUREDATE", "Departuredate", DataTypes.stringType()), 
                         Columns.column(" ORIGIN", "Origin", DataTypes.stringType()),
                                    Columns.column(" DESTINATION", "Destination", DataTypes.stringType()),
                                  Columns.column(" PAYMENT", "Payment", DataTypes.stringType()),
                                   Columns.column(" TRANSACTION  ","Transaction", DataTypes.stringType()),
                                    Columns.column(" GENDER", "Gender", DataTypes.stringType()) 
                          
                 )
                 .title(//title of the report
	      Components.text(" CANCELLATION LIST ")
                      .setStyle(boldCenteredStyle)
                  .setHorizontalTextAlignment(HorizontalTextAlignment.CENTER)
		  )
                .setColumnTitleStyle(columnTitleStyle) 
                
		  .pageFooter(Components.pageXofY())//show page number on the page footer

                .pageFooter(Components.pageXofY())//show page number on the page footer

// SET DATA SOURCE
                .setDataSource(qry, con);
       try {
//show the report
            report.show(false);
//export the report to a pdf file
//report.toPdf(new FileOutputStream("c:/report.pdf"));
        } catch (DRException e) {
            e.printStackTrace();
        }
    }
      
      

       
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
