/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;


 


import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static net.sf.dynamicreports.examples.Templates.boldCenteredStyle;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import static net.sf.dynamicreports.report.builder.DynamicReports.stl;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalTextAlignment;
import net.sf.dynamicreports.report.exception.DRException;

/**
 *
 * @author 
 */
public class Customer extends javax.swing.JInternalFrame {

    private final DefaultTableModel model;
    
    

  
    

   
    

    /**
     * Creates new form CUSTOMER
     */
    public Customer( ) {
      
        model = new DefaultTableModel();
         
   
        initComponents();
           showData();
            getMaxId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setClosable(true);
        setFrameIcon(null);
        setName(""); // NOI18N
        setOpaque(true);
        setVisible(true);

        jPanel1.setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("ID");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, 110, 40, 30);

        jTextField1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel3.add(jTextField1);
        jTextField1.setBounds(180, 110, 130, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("NAME");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 150, 80, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("CONTACT");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 190, 120, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("ADDRESS");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 230, 110, 30);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setText("GENDER");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 270, 100, 30);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel8.setText("AGE");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(90, 310, 60, 30);

        jTextField2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel3.add(jTextField2);
        jTextField2.setBounds(180, 150, 130, 30);

        jTextField3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(180, 190, 130, 30);

        jTextField4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel3.add(jTextField4);
        jTextField4.setBounds(180, 230, 130, 30);

        jTextField5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(180, 270, 130, 30);

        jTextField6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel3.add(jTextField6);
        jTextField6.setBounds(180, 310, 130, 29);

        jButton1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton1.setText("ADD ");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(30, 370, 100, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTable1.setModel(model);
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(330, 110, 540, 240);

        jButton2.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(150, 410, 130, 30);

        jButton3.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(150, 370, 130, 30);

        jButton4.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton4.setText("BACK  TO MENU");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(300, 410, 210, 30);

        jButton5.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton5.setText("NEW");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(30, 410, 100, 30);

        jButton6.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jButton6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton6.setText("REPORT");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(300, 370, 130, 30);

        jRadioButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton1.setText(" RESERVE");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(530, 410, 140, 40);

        jRadioButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton2.setText("ENQURY");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(670, 410, 120, 40);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel2.setText("CUSTOMER DETAILS");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(230, 30, 390, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 880, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 470);

        jButton7.setText("RESERVATION");
        jPanel1.add(jButton7);
        jButton7.setBounds(540, -10, 103, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
        insert();
          showData();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
          Home h = new Home();
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

         // TODO add your handling code here:
  updateData();
        showData();
       
 
  
   
  
  
   
        
          
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
   deleteData();
    showData();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           loadData();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           getMaxId();
            clearData();
           
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        generateReport();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         SearchFlight v   =new SearchFlight();
           JDesktopPane  desktopPane = getDesktopPane();
           desktopPane.add(v);
           v.setVisible(true);
           this.dispose();
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

        
        
void clearData()
      {
          jTextField2.setText("");
          jTextField3.setText("");
          jTextField4.setText("");
          jTextField5.setText("");
          jTextField6.setText("");
      }
    
 
 void insert(){
          Connection con = null;//initializing connection object
          PreparedStatement pr=null;
          String qry;
          String url;
          
          try{
              
              File path= new File(System.getProperty("user.dir"));
                url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
              qry =  "insert into Customer(id,name,contact,address,Gender,Age) values(?,?,?,?,?,?)";
             con = DriverManager.getConnection(url);
             pr=con.prepareStatement(qry);
            
             
            pr.setInt(1,Integer.parseInt(jTextField1.getText()));
            pr.setString(2,jTextField2.getText());
             pr.setString(3,jTextField3.getText());
             pr.setString(4,jTextField4.getText());
              pr.setString(5,jTextField5.getText());
               pr.setInt(6,Integer.parseInt(jTextField6.getText()));
            
            
        
              
             
             
             int result=pr.executeUpdate();
            if(result>0)
              JOptionPane.showMessageDialog(rootPane, "inserted");
             con.close();
             
             
              
          }catch(Exception e){
              JOptionPane.showMessageDialog(rootPane, e);
              
          }
          
      }



          
    
    
    // -------------------- SHOW DATA ----------
      void showData(){
        int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null; 
    try{
         
         
        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="SELECT  * FROM customer  ";  
        con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
         
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
        
    }
      void loadData(){
        
          
            DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        jTextField1.setEditable(true);
        int rowindex = jTable1.getSelectedRow();
        
            jTextField1.setText(m1.getValueAt(rowindex, 4).toString());
            jTextField2.setText(m1.getValueAt(rowindex, 0).toString());
            jTextField3.setText(m1.getValueAt(rowindex, 1).toString());
          jTextField4.setText(m1.getValueAt(rowindex,2).toString());
          jTextField5.setText(m1.getValueAt(rowindex,3).toString());
          jTextField6.setText(m1.getValueAt(rowindex, 5).toString());
        
        jTextField1.setEditable(false);
    }
       void deleteData(){
         Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    
     DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        
        int rowindex = jTable1.getSelectedRow();
        if(rowindex<0)
        {
            JOptionPane.showMessageDialog(rootPane, "No value is selected to delete");
            return;
        }
           int id= Integer.parseInt(m1.getValueAt(rowindex, 1).toString());
    
    
    
     try{
       
         
        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="delete  from Customer where  id = "+jTextField1.getText()   ;  
        con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
        //pr.setInt(0,id);
       
        int result= pr.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
        
                
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
    
    }
    
       
       void updateData( ){
     Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
   
    try{
             File path = new File(System.getProperty("user.dir"));
             url = "jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
           qry="update Customer set  Name='"+jTextField2.getText()+"' ,Contact ='"+jTextField3.getText()+ "', Address ='"+jTextField4.getText()+"' ,Gender='"+jTextField5.getText()+"' , Age= '"+jTextField6.getText()+"' where  ID='"+jTextField1.getText()+"'";
        
        con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
            
        
        
        int result= pr.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
        
                
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
     
        
        
    }
     void getMaxId(){
        jTextField1.setEditable(true);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
         File path = new File(System.getProperty("user.dir"));
         url = "jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="select MAX( id)+1  from Customer";
        con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
       
        while(rs.next()){
          jTextField1 .setText(rs.getString(1));
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
    }  
       
    private void generateReport() {   
    Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
        
        
       
        try {

        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";


// SearchFlight QUERY 

        qry="select * from Customer";
        con=DriverManager.getConnection(url);
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }
        
       

                StyleBuilder columnTitleStyle  = stl.style(boldCenteredStyle)

                                    .setBorder(stl.pen1Point())
                                    .setBackgroundColor(Color.BLUE);

        
       JasperReportBuilder report = DynamicReports.report();//a new report
         report
                .setColumnTitleStyle(columnTitleStyle)
               // .setColumnStyle(boldStyle)
                .columns(
                        Columns.column("ID", "id",   DataTypes.stringType()),
                        Columns.column("NAME", "Name", DataTypes.stringType()),
                        Columns.column("CONTACT", "Contact", DataTypes.stringType()),
                        Columns.column("ADDRESS", "Address", DataTypes.stringType()),
                        Columns.column("Gender", "Gender", DataTypes.stringType()),
                       Columns.column("AGE", "Age", DataTypes.stringType())
                )
                  .title(//title of the report
	      Components.text(" CUSTOMER LIST ")
                      .setStyle(boldCenteredStyle)
                  .setHorizontalTextAlignment(HorizontalTextAlignment.CENTER)
		  )
                .setColumnTitleStyle(columnTitleStyle) 
                
		  .pageFooter(Components.pageXofY())//show page number on the page footer

                .pageFooter(Components.pageXofY())//show page number on the page footer

// SET DATA SOURCE
                .setDataSource(qry, con);
       try {
//show the report
            report.show(false);
//export the report to a pdf file
//report.toPdf(new FileOutputStream("c:/report.pdf"));
        } catch (DRException e) {
            e.printStackTrace();
        }
    }
      
      



     
 
  
        
 
    
    
    
    

 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}