/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class Delete extends javax.swing.JInternalFrame {

    /**
     * Creates new form Delete
     */
     private final DefaultTableModel model;
    public Delete() {
          model = new DefaultTableModel();
        initComponents();
  
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ViewAButton = new javax.swing.JButton();
        ViewMButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jRadioButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton1.setText("INTERNATIONAL");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(19, 7, 230, 37);

        jRadioButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton2.setText(" DOMASTIC");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(351, 7, 218, 37);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(140, 100, 610, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setText("DELETE FLIGHT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 10, 320, 60);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 650, 140);

        ViewAButton.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        ViewAButton.setText("Delete Flight Schedule");
        ViewAButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ViewAButton.setContentAreaFilled(false);
        ViewAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ViewAButton);
        ViewAButton.setBounds(40, 270, 300, 40);

        ViewMButton.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        ViewMButton.setText("Menu Admin");
        ViewMButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ViewMButton.setContentAreaFilled(false);
        ViewMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ViewMButton);
        ViewMButton.setBounds(370, 270, 210, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText(" ");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(10, 160, 130, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText(" ");
        jPanel3.add(jTextField2);
        jTextField2.setBounds(200, 160, 120, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setText(" ");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(360, 160, 130, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setText(" ");
        jPanel3.add(jTextField4);
        jTextField4.setBounds(530, 160, 130, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setText(" ");
        jPanel3.add(jTextField5);
        jTextField5.setBounds(10, 210, 130, 40);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.setText(" ");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(200, 210, 120, 40);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setText(" ");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(360, 210, 130, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setText(" ");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(530, 210, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 140, 670, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         showData();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         showData();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void ViewMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMButtonActionPerformed

        Admin  M=new  Admin();
        JDesktopPane  desktopPane = getDesktopPane();
        desktopPane.add(M);
        M.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ViewMButtonActionPerformed

    private void ViewAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAButtonActionPerformed
        deleteData();
          showData();

    }//GEN-LAST:event_ViewAButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         loadData();
    }//GEN-LAST:event_jTable1MouseClicked

 
    
  void showData(){
        int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
         File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
         if(jRadioButton1.isSelected())
         {
        qry="select  *  from Iflightrecords ";
         }
         else{
               qry="select  *  from  Dflightrecords ";
         }
        con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
        
    }
  void deleteData(){
         Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    
     DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        
        int rowindex = jTable1.getSelectedRow();
        if(rowindex<0)
        {
            JOptionPane.showMessageDialog(rootPane, "No value is selected to delete");
            return;
        }
            
    
    
    
     try{
       
         File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
         
        if(jRadioButton1.isSelected())
         {
                     qry="delete from Iflightrecords where flightno= "+jTextField8.getText()   ;  
         }
         
         
       if(jRadioButton2.isSelected())
         
         {
             qry="delete from Dflightrecords where Flightno= "+jTextField1.getText()   ; 
         }
        con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
        
       
        int result= pr.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
        
                
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
    
    }
   void loadData(){
        DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        jTextField7.setEditable(true);
        int rowindex = jTable1.getSelectedRow();
        jTextField1.setText(m1.getValueAt(rowindex, 0).toString());
            jTextField2.setText(m1.getValueAt(rowindex, 1).toString());
            jTextField3.setText(m1.getValueAt(rowindex, 2).toString());
            jTextField4.setText(m1.getValueAt(rowindex, 3).toString());
            jTextField5.setText(m1.getValueAt(rowindex, 4).toString());
             jTextField6.setText(m1.getValueAt(rowindex, 5).toString());
             jTextField7.setText(m1.getValueAt(rowindex, 6).toString());
             jTextField8.setText(m1.getValueAt(rowindex, 7).toString());
        jTextField7.setEditable(false);
   }
     
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAButton;
    private javax.swing.JButton ViewMButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
