




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class FlightBook extends javax.swing.JInternalFrame {

    String  flightno2,Origin2,Destination2,date2,des,Avt,cst,pay,flg ,date;
    private final DefaultTableModel model;
     /**
     * Creates new form seat
     */
    public FlightBook() {
  
        model = new DefaultTableModel();
            
        initComponents();
     
    }
    public void FlightDetails(String Flightno,String Origin,String Destination ,String date){
         jTextField1.setText(Origin);
        jTextField3.setText(Destination);
        jTextField2.setText(Flightno);
        jTextField10.setText(date);
        Origin2 = Origin;
        Destination2 = Destination;
         flightno2= Flightno;
         date2=date;
    }
         
        
   
        
     
    
        
       
    

     
      
     
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Flight No. :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 310, 100, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(230, 310, 190, 30);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 850, 160);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(500, 430, 130, 35);

        jRadioButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton1.setText("INTERNNATION");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(210, 30, 210, 30);

        jRadioButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton2.setText("DOMASTIC");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(440, 30, 170, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Destination :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 270, 140, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Origin :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 230, 110, 30);

        jTextField1.setText(" ");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(230, 230, 190, 30);

        jTextField3.setText(" ");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(230, 270, 190, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Airliner :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 390, 90, 30);

        jTextField4.setText(" ");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(230, 390, 190, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Arrival Time :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(450, 270, 160, 30);

        jTextField5.setText(" ");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(600, 270, 190, 30);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Departure Time :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 310, 160, 30);

        jTextField6.setText(" ");
        jPanel2.add(jTextField6);
        jTextField6.setBounds(600, 310, 190, 30);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Price :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(450, 230, 130, 30);

        jTextField7.setText(" ");
        jPanel2.add(jTextField7);
        jTextField7.setBounds(600, 230, 190, 30);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Days");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 350, 50, 30);

        jTextField8.setText(" ");
        jPanel2.add(jTextField8);
        jTextField8.setBounds(600, 350, 190, 30);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Seats");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(450, 390, 90, 30);

        jTextField9.setText(" ");
        jPanel2.add(jTextField9);
        jTextField9.setBounds(600, 390, 190, 30);

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Date :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(90, 350, 60, 30);

        jTextField10.setText(" ");
        jPanel2.add(jTextField10);
        jTextField10.setBounds(230, 350, 190, 30);

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel12.setText("Flight");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(90, 430, 70, 30);

        jTextField11.setText(" ");
        jPanel2.add(jTextField11);
        jTextField11.setBounds(230, 430, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 470);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        des=jTextField6.getText() ;
        Avt=jTextField5.getText() ;
         flg=jTextField11.getText();
        pay=jTextField7.getText() ; 
        date2 =jTextField10.getText();
        Reservation  i=new  Reservation();
           JDesktopPane  desktopPane = getDesktopPane();
           desktopPane.add( i);
            i.show(flightno2,Origin2,Destination2,date2,des,Avt ,pay,flg);
           i.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
            showData1();
            
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
           showData1();
            
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
     
        
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jTable1MouseClicked
  
   void showData1(){
       int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
         File path = new File(System.getProperty("user.dir"));
         url = "jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
          
         if(jRadioButton1.isSelected())
         {
             
          qry="SELECT * FROM  IFlightRecords where FlightNo='"+jTextField2.getText()+"' and Date='"+jTextField10.getText()+"' ";

          
         } if(jRadioButton2.isSelected())
          {  
              qry="SELECT * FROM DFlightRecords where FlightNo='"+jTextField2.getText()+"' and Date='"+jTextField10.getText()+"'  ";
   
        
         }
       
        con=DriverManager.getConnection(url);
         
      
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
    
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }
  void loadData(){
       DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
    
        int rowindex = jTable1.getSelectedRow();
        
             if(jRadioButton1.isSelected())
             {
            jTextField1.setText(m1.getValueAt(rowindex, 2).toString());
            jTextField2.setText(m1.getValueAt(rowindex, 6).toString());
            jTextField3.setText(m1.getValueAt(rowindex, 1).toString());
            jTextField4.setText(m1.getValueAt(rowindex, 0).toString());
             jTextField5.setText(m1.getValueAt(rowindex, 3).toString());
            jTextField6.setText(m1.getValueAt(rowindex, 4).toString());
            jTextField7.setText(m1.getValueAt(rowindex,10).toString());
           jTextField8.setText(m1.getValueAt(rowindex, 5).toString());
        jTextField9.setText(m1.getValueAt(rowindex, 8).toString());
          jTextField10.setText(m1.getValueAt(rowindex,7).toString());
           jTextField11.setText(m1.getValueAt(rowindex,9).toString());
    }
         if(jRadioButton2.isSelected())
          {     
               jTextField1.setText(m1.getValueAt(rowindex, 3).toString());
            jTextField2.setText(m1.getValueAt(rowindex, 0).toString());
            jTextField3.setText(m1.getValueAt(rowindex, 2).toString());
            jTextField4.setText(m1.getValueAt(rowindex, 1).toString());
             jTextField5.setText(m1.getValueAt(rowindex, 4).toString());
            jTextField6.setText(m1.getValueAt(rowindex, 5).toString());
            jTextField7.setText(m1.getValueAt(rowindex,9).toString());
           jTextField8.setText(m1.getValueAt(rowindex, 6).toString());
        jTextField9.setText(m1.getValueAt(rowindex, 10).toString());
          jTextField10.setText(m1.getValueAt(rowindex,7).toString());
           jTextField11.setText(m1.getValueAt(rowindex,8).toString());
          }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

     
   

    
    
    
   
    
}
