 
package Forms;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Shrikant Dewangan
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form DONE
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        my = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        my2 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        oo = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("Username :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(170, 130, 150, 30);

        my.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        my.setSelectionColor(new java.awt.Color(0, 0, 153));
        jPanel3.add(my);
        my.setBounds(360, 130, 210, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Password :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(170, 170, 150, 30);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton1.setText("Ok");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(590, 130, 130, 30);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(590, 170, 130, 30);

        my2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        my2.setSelectionColor(new java.awt.Color(0, 0, 153));
        jPanel3.add(my2);
        my2.setBounds(360, 170, 210, 30);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel4.setText("FORGET  PASSWORD");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(190, 20, 260, 40);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Question :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 80, 100, 20);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText(" Enter Your E-Mail ID ???");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(200, 70, 220, 40);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Answer :");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 110, 100, 30);

        jTextField1.setText(" ");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(jTextField1);
        jTextField1.setBounds(200, 110, 210, 30);

        jButton3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton3.setText("Ok");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(470, 80, 120, 30);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(jButton4);
        jButton4.setBounds(470, 120, 120, 30);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("New Password :");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 150, 150, 30);

        oo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.add(oo);
        oo.setBounds(200, 150, 210, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(130, 220, 630, 230);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setText("USER  LOGIN");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(270, 40, 370, 57);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
login();
// TODO add your handling code here:
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Home   kent34 = new Home();
        this.dispose();
        kent34.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        forget();
    }//GEN-LAST:event_jButton3ActionPerformed
  void login()
  {
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null; 
    try{
        
       File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="SELECT *  FROM LOGIN where  username=? and Password =? ";

           con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
   pr.setString(1,my .getText());
        pr.setString(2,my2.getText());
              
        rs= pr.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null,"successfully login");
            Admin l   =new Admin();
           JDesktopPane  desktopPane = getDesktopPane();
           desktopPane.add(l);
           l.setVisible(true);
           this.dispose();
         }
        else
        {
                        JOptionPane.showMessageDialog(null,"  login failed");

        }
  }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
  }
  void forget()
  {
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
     
    try{
        
        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        qry="update  LOGIN set Password = '"+oo.getText()+ "'  where  answer ='"+jTextField1.getText()+ "'";
 con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
         
         
      int result=pr.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"successfully changed");
       
                        
            
            

         
  }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField my;
    private javax.swing.JPasswordField my2;
    private javax.swing.JPasswordField oo;
    // End of variables declaration//GEN-END:variables

}
