/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manali
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {
private final DefaultTableModel model;
    /**
     * Creates new form NewJInternalFrame
     */
    public NewJInternalFrame()
    
    {
           model = new DefaultTableModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Flightno");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 10, 130, 40);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Airliner");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 70, 130, 60);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Destination");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 140, 100, 50);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("Origin");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 210, 130, 40);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Arrival TIme");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 270, 110, 60);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Departure Time");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 340, 170, 30);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Price");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(370, 10, 90, 30);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Days");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(370, 80, 60, 20);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Date");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 140, 80, 30);

        jTextField1.setText(" ");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(200, 20, 110, 40);

        jTextField2.setText(" ");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(200, 80, 110, 40);

        jTextField3.setText(" ");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(200, 150, 110, 40);

        jTextField4.setText(" ");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(200, 210, 110, 40);

        jTextField5.setText(" ");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(200, 280, 110, 40);

        jTextField6.setText(" ");
        jPanel2.add(jTextField6);
        jTextField6.setBounds(200, 350, 110, 40);

        jTextField7.setText(" ");
        jPanel2.add(jTextField7);
        jTextField7.setBounds(450, 10, 100, 40);

        jTextField8.setText(" ");
        jPanel2.add(jTextField8);
        jTextField8.setBounds(450, 80, 100, 40);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton1.setText("Proceed");
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 400, 270, 80);

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(340, 260, 460, 190);
        jPanel2.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(450, 140, 110, 40);

        jRadioButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton1.setText("INTERNATIONAL");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(340, 190, 230, 50);

        jRadioButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton2.setText("DOMESTIC ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(590, 190, 220, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 20, 820, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/wackiest-airplanes-plane1215.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jRadioButton2ActionPerformed
void showData1(){
        int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
        
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
         File path= new File(System.getProperty("user.dir"));
        url="jdbc:mysql://localhost:3306/airlines";
         if(jRadioButton1.isSelected())
         {
        qry="select  * from  Iflightrecords where Origin=? && Destination=?"  ; 
         }
         else{
             
              qry="select    * from Dfightrecords   where Origin=? && Destination=?";
         }
        con=DriverManager.getConnection(url);
         
      
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
