/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
public class Update extends javax.swing.JInternalFrame {
 private final DefaultTableModel model;
    /**
     * Creates new form UPDATE
     */
    public Update() {
         model = new DefaultTableModel();
  
         
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setLayout(null);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Flight No. :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 160, 140, 30);

        jTextField2.setText(" ");
        jPanel3.add(jTextField2);
        jTextField2.setBounds(240, 160, 198, 30);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Departure Time :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 240, 210, 30);

        jTextField3.setText(" ");
        jPanel3.add(jTextField3);
        jTextField3.setBounds(240, 200, 198, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("Airliner :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 200, 120, 30);

        jTextField4.setText(" ");
        jPanel3.add(jTextField4);
        jTextField4.setBounds(240, 240, 198, 30);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setText("Price :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 280, 90, 30);

        jTextField5.setText(" ");
        jPanel3.add(jTextField5);
        jTextField5.setBounds(240, 280, 198, 30);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(260, 340, 140, 30);

        jButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton2.setText("Back To Admin");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(410, 340, 200, 30);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(450, 160, 420, 150);

        jRadioButton1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton1.setText("International");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(190, 110, 260, 30);

        jRadioButton2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jRadioButton2.setText("Domestic");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(460, 110, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setText("UPDATE FLIGHT");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 30, 330, 43);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 890, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Image.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        updateData();
          showData();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Admin a =new  Admin();
           JDesktopPane  desktopPane = getDesktopPane();
           desktopPane.add(a);
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
     
        loadData();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         showData();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
                  showData();
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed
void showData(){
        int row_count = model.getRowCount();
        if(row_count>0)
            for( int i = row_count-1;i>=0;i--)
                model.removeRow(i);
        
        model.setColumnCount(0);
        Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
    ResultSet rs = null;
    try{
        
        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
        if(jRadioButton1.isSelected() )
        {
        qry="select flightno,airliner,Departuretime,Eprice  from  Iflightrecords";
     
       
        }
        
          if(jRadioButton2.isSelected() )
        {
            qry="select  flightno,airliner,Departuretime ,Eprice   from Dflightrecords  ";
        }
    
          
        

        
            
        con=DriverManager.getConnection(url);
        pr= con.prepareStatement(qry);
        
        rs= pr.executeQuery();
        ResultSetMetaData rsmd = rs.getMetaData();
        int col_count= rsmd.getColumnCount();
        
        for( int i = 0;i< col_count;i++){
            String col_name= rsmd.getColumnName(i+1);
            model.addColumn(col_name);
        }
        while(rs.next()){
            Vector v= new Vector();
            for (int i=0;i<col_count;i++)
                v.add(rs.getString(i+1));
            model.addRow(v);
        }
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    
}
    void loadData(){
        DefaultTableModel m1 = (DefaultTableModel) jTable1.getModel();
        jTextField2.setEditable(true);
        int rowindex = jTable1.getSelectedRow();
        
            
        
            jTextField2.setText(m1.getValueAt(rowindex, 0).toString());
            jTextField3.setText(m1.getValueAt(rowindex, 1).toString());
            jTextField4.setText(m1.getValueAt(rowindex, 2).toString());
             jTextField5.setText(m1.getValueAt(rowindex, 3).toString());
           
            
           
        
        jTextField2.setEditable(false);
    }
     
    void updateData(){
         Connection con = null;
    PreparedStatement pr = null;
    String url = null;
    String qry= null;
   
    try{
       
        
        File path= new File(System.getProperty("user.dir"));
        url="jdbc:ucanaccess://"+path.getPath()+"/airlines.accdb";
           if(jRadioButton2.isSelected())
                
        {
        qry="update Dflightrecords set airliner ='"+jTextField3.getText()+"' , Departuretime ='"+jTextField4.getText()+"',   Eprice ='"+jTextField5.getText()+"'  where flightno='"+jTextField2.getText()+"'";
        }
           
           if(jRadioButton1.isSelected())
                
        { 
        qry="update  Iflightrecords set airliner ='"+jTextField3.getText()+"' , Departuretime ='"+jTextField4.getText()+"',Eprice ='"+jTextField5.getText()+"'   where flightno='"+jTextField2.getText()+"'";
        }
        con=DriverManager.getConnection(url);
        pr=con.prepareStatement(qry);
         
        
        int result= pr.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
        
                
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
     
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
